### ISSUE TITLE
Hi, cannot find violet void theme

### ISSUE THREAD

**Issue by HorridModz** [aaronedev/aaronedev#2]
Hi, stumbled across your profile and I'm interested in voilet void theme! I tried to go to the [website](https://violet-void-theme.com/) and got a 403 forbidden error; there also doesn't seem to be a public repository for it on your github. Is this not finished, or just not yet published? If you can share it, I'm excited to check it out!

**Comment by aaronedev** [comment]
Hey @HorridModz!

At the moment, the theme isn't finished, and that's why you encountered the 403 error. However, I just created a public [repository](https://github.com/aaronedev/violet-void-theme) of Violet Void Theme where you can follow the development. I am currently working on a first release, which will be a minimal version without all the features I plan to include in the final version.

Please feel free to follow the repository, and I'll keep it updated as I make progress. I tend to work on multiple projects based on how I feel, so the pace might vary, but I will release that initial version soon.

Looking forward to staying in touch!

**Comment by HorridModz** [comment]
> Hey @HorridModz!
> 
> At the moment, the theme isn't finished, and that's why you encountered the 403 error. However, I just created a public [repository](https://github.com/aaronedev/violet-void-theme) of Violet Void Theme where you can follow the development. I am currently working on a first release, which will be a minimal version without all the features I plan to include in the final version.
> 
> Please feel free to follow the repository, and I'll keep it updated as I make progress. I tend to work on multiple projects based on how I feel, so the pace might vary, but I will release that initial version soon.
> 
> Looking forward to staying in touch!

Nice! I'm intrigued because I've never heard of a Windows theme (though I'm sure there's many), and surely a cool person on Github can do a better job than Microsoft's shit.

**Comment by HorridModz** [comment]
Should I close this issue? Perhaps the link could be changed to the repository instead of the website.

**Comment by aaronedev** [comment]
> > Hey @HorridModz!
> > At the moment, the theme isn't finished, and that's why you encountered the 403 error. However, I just created a public [repository](https://github.com/aaronedev/violet-void-theme) of Violet Void Theme where you can follow the development. I am currently working on a first release, which will be a minimal version without all the features I plan to include in the final version.
> > Please feel free to follow the repository, and I'll keep it updated as I make progress. I tend to work on multiple projects based on how I feel, so the pace might vary, but I will release that initial version soon.
> > Looking forward to staying in touch!
> 
> Nice! I'm intrigued because I've never heard of a Windows theme (though I'm sure there's many), and surely a cool person on Github can do a better job than Microsoft's shit.

haha oh well i think most people can do a better job than microsoft haha. I'll let you know once i release a preview version :)

**Comment by aaronedev** [comment]
> Should I close this issue? Perhaps the link could be changed to the repository instead of the website.

i fixed it and will close it thanks tho:)
